name: Deploy

on:
  workflow_dispatch:
  pull_request:
  push:
    branches: master

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: pages
  cancel-in-progress: true

jobs:
  website:
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:

    - name: Setup Pages
      id: pages
      uses: actions/configure-pages@v2

    - uses: actions/checkout@v3
      with:
        submodules: recursive

    - name: Build the site
      run: pipx run nox -s build

    - name: Upload artifact
      uses: actions/upload-pages-artifact@v1
      with:
        path: output

    - name: Deploy to GitHub Pages
      id: deployment
      if: github.ref == 'refs/heads/master'
      uses: actions/deploy-pages@v1
