name: Test

on:
  workflow_dispatch:
  pull_request:

permissions: {}

concurrency:
  group: pages
  cancel-in-progress: true

jobs:
  website:
    runs-on: ubuntu-latest
    steps:

    - uses: actions/checkout@v3
      with:
        submodules: recursive
        persist-credentials: false

    - name: Build the site
      run: pipx run nox -s build

